"""empty message

Revision ID: 508d280506ae
Revises: 
Create Date: 2018-10-31 21:44:50.408208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '508d280506ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('json_data', mysql.TEXT(), nullable=True),
                    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('project', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('count', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"),
                              autoincrement=False, nullable=False),
                    sa.Column('title', mysql.VARCHAR(length=500), nullable=True),
                    sa.Column('state', mysql.VARCHAR(length=50), server_default=sa.text("'open'"), nullable=False),
                    sa.Column('description', mysql.TEXT(), nullable=True),
                    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('closed_at', mysql.DATETIME(), nullable=True),
                    sa.Column('closed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('discussion_locked', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['closed_by'], ['user.id'], name='issues_ibfk_3'),
                    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='issues_ibfk_2'),
                    sa.ForeignKeyConstraint(['project'], ['project.id'], name='issues_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )


op.create_index('project_count', 'issues', ['project', 'count'], unique=True)
op.create_table('user',
                sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                sa.Column('json_data', mysql.TEXT(), nullable=True),
                sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                          nullable=False),
                sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                          nullable=False),
                sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
                sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=True),
                sa.Column('photo_url', mysql.VARCHAR(length=2013), nullable=True),
                sa.Column('email', mysql.VARCHAR(length=200), nullable=True),
                sa.Column('firebase_uid', mysql.VARCHAR(length=100), nullable=True),
                sa.Column('admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"),
                          autoincrement=False, nullable=False),
                sa.PrimaryKeyConstraint('id'),
                mysql_collate='utf8mb4_0900_ai_ci',
                mysql_default_charset='utf8mb4',
                mysql_engine='InnoDB'
                )
op.create_table('project',
                sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                sa.Column('json_data', mysql.TEXT(), nullable=True),
                sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                          nullable=False),
                sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'),
                          nullable=False),
                sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
                sa.Column('owner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                sa.Column('issue_counter', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"),
                          autoincrement=False, nullable=False),
                sa.Column('dame', mysql.VARCHAR(length=200), nullable=True),
                sa.ForeignKeyConstraint(['owner'], ['user.id'], name='project_ibfk_1'),
                sa.PrimaryKeyConstraint('id'),
                mysql_collate='utf8mb4_0900_ai_ci',
                mysql_default_charset='utf8mb4',
                mysql_engine='InnoDB'
                )


# ### end Alembic commands ###


def downgrade():
    pass
